version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ezpaarse-homepage_nginx
    ports:
      -  ${NGINX_PORT:-80}:80
    environment:
      # proxy
      - http_proxy
      - https_proxy
      - NODE_ENV=production
      - NGINX_HOST
    volumes:
      - "./templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro"
    restart: unless-stopped